CREATE TABLE PRODUCTS (
  ID INTEGER NOT NULL,
  TITLE VARCHAR(255) NOT NULL,
  KEYWORDS VARCHAR(255) NOT NULL,
  DESCRIPTION VARCHAR(255) NOT NULL,
  CREATED TIME DEFAULT NOW(),
  UPDATED TIME DEFAULT NOW(),
  PRIMARY KEY(ID)
);

CREATE SEQUENCE SEQ_PRODUCT START WITH 1 NO CYCLE CACHE 1 OWNED BY PRODUCTS.ID;

CREATE TABLE MENU (
  ID INTEGER NOT NULL,
  NAME VARCHAR(50) NOT NULL,
  CODE VARCHAR(15) NOT NULL,
  CREATED TIME DEFAULT NOW(),
  UPDATED TIME DEFAULT NOW(),
  PRIMARY KEY(ID)
);

CREATE SEQUENCE SEQ_MENU START WITH 1 NO CYCLE CACHE 1 OWNED BY MENU.ID;

CREATE TABLE MENU_ITEMS (
  ID INTEGER NOT NULL,
  NAME VARCHAR(50) NOT NULL,
  CODE VARCHAR(15) NOT NULL,
  MENU_ID INTEGER REFERENCES MENU(ID),
  CREATED TIME DEFAULT NOW(),
  UPDATED TIME DEFAULT NOW(),
  PRIMARY KEY(ID)
);

CREATE SEQUENCE SEQ_MENU_ITEM START WITH 1 NO CYCLE CACHE 1 OWNED BY MENU_ITEMS.ID;

CREATE TABLE PAGES (
  ID INTEGER NOT NULL,
  TITLE VARCHAR(255) NOT NULL,
  KEYWORDS VARCHAR(255) NOT NULL,
  DESCRIPTION VARCHAR(255) NOT NULL,
  CREATED TIME DEFAULT NOW(),
  UPDATED TIME DEFAULT NOW(),
  PRIMARY KEY(ID)
);

CREATE SEQUENCE SEQ_PAGES START WITH 1 NO CYCLE CACHE 1 OWNED BY PAGES.ID;

delete from PRODUCTS;
COMMIT ;