CREATE TABLE PROJECTS (
  ID          INTEGER      NOT NULL,
  TITLE       VARCHAR(255) NOT NULL,
  CODE        VARCHAR(50)  NOT NULL,
  HOST        VARCHAR(50)  NOT NULL,
  DESCRIPTION VARCHAR(255) NOT NULL,
  CREATED     TIME DEFAULT NOW(),
  UPDATED     TIME DEFAULT NOW(),
  PRIMARY KEY (ID)
);
CREATE SEQUENCE SEQ_PROJECTS
  START WITH 1
  NO CYCLE
  CACHE 1
  OWNED BY PROJECTS.ID;

CREATE TABLE CATALOG (
  ID          INTEGER      NOT NULL,
  TITLE       VARCHAR(255) NOT NULL,
  KEYWORDS    VARCHAR(255) NOT NULL,
  DESCRIPTION VARCHAR(255) NOT NULL,
  SLUG        VARCHAR(50)  NOT NULL,
  PROJECT_ID  INTEGER REFERENCES PROJECTS (ID),
  CREATED     TIME DEFAULT NOW(),
  UPDATED     TIME DEFAULT NOW(),
  PRIMARY KEY (ID)
);
CREATE SEQUENCE SEQ_CATALOG
  START WITH 1
  NO CYCLE
  CACHE 1
  OWNED BY CATALOG.ID;

CREATE TABLE PRODUCTS (
  ID          INTEGER      NOT NULL,
  TITLE       VARCHAR(255) NOT NULL,
  KEYWORDS    VARCHAR(255) NOT NULL,
  DESCRIPTION VARCHAR(255) NOT NULL,
  SLUG        VARCHAR(50)  NOT NULL,
  PROJECT_ID  INTEGER REFERENCES PROJECTS (ID),
  CATALOG_ID  INTEGER REFERENCES CATALOG (ID),
  CREATED     TIME DEFAULT NOW(),
  UPDATED     TIME DEFAULT NOW(),
  PRIMARY KEY (ID)
);
CREATE SEQUENCE SEQ_PRODUCTS
  START WITH 1
  NO CYCLE
  CACHE 1
  OWNED BY PRODUCTS.ID;

CREATE TABLE MENU (
  ID         INTEGER     NOT NULL,
  NAME       VARCHAR(50) NOT NULL,
  CODE       VARCHAR(15) NOT NULL,
  PROJECT_ID INTEGER REFERENCES PROJECTS (ID),
  CREATED    TIME DEFAULT NOW(),
  UPDATED    TIME DEFAULT NOW(),
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_MENU
  START WITH 1
  NO CYCLE
  CACHE 1
  OWNED BY MENU.ID;

CREATE TABLE MENU_ITEMS (
  ID         INTEGER     NOT NULL,
  NAME       VARCHAR(50) NOT NULL,
  CODE       VARCHAR(15) NOT NULL,
  MENU_ID    INTEGER REFERENCES MENU (ID),
  PROJECT_ID INTEGER REFERENCES PROJECTS (ID),
  CREATED    TIME DEFAULT NOW(),
  UPDATED    TIME DEFAULT NOW(),
  PRIMARY KEY (ID)
);
CREATE SEQUENCE SEQ_MENU_ITEMS
  START WITH 1
  NO CYCLE
  CACHE 1
  OWNED BY MENU_ITEMS.ID;

CREATE TABLE PAGES (
  ID          INTEGER      NOT NULL,
  TITLE       VARCHAR(255) NOT NULL,
  KEYWORDS    VARCHAR(255) NOT NULL,
  DESCRIPTION VARCHAR(255) NOT NULL,
  SLUG        VARCHAR(50)  NOT NULL,
  PROJECT_ID  INTEGER REFERENCES PROJECTS (ID),
  CREATED     TIME DEFAULT NOW(),
  UPDATED     TIME DEFAULT NOW(),
  PRIMARY KEY (ID)
);
CREATE SEQUENCE SEQ_PAGES
  START WITH 1
  NO CYCLE
  CACHE 1
  OWNED BY PAGES.ID;