CREATE OR REPLACE FUNCTION CALCULATE_CSTMR_FULLNAME()
  RETURNS trigger AS $$
BEGIN
  NEW.FULL_NAME = UPPER(NEW.FIRST_NAME || ' ' || NEW.LAST_NAME || ' ' || NEW.SECOND_NAME);
  RETURN NEW;
END;
$$ LANGUAGE 'plpgsql';

CREATE TRIGGER CALCULATE_CSTMR_FULLNAME
  BEFORE INSERT
  ON CUSTOMERS
  FOR EACH ROW
  EXECUTE PROCEDURE CALCULATE_CSTMR_FULLNAME();